---
# tasks file for basic-tools


# ansible_user_dir
# ansible_user_id
# ansible_user_shell

- name: Check sudo
  debug:
    var: ansible_become

- name: Install Packages
  apt:
    update_cache: true
    state: present
    name:
      - tree
      - git
  become: true

- name: Ensure dirs like ~/bin exist
  file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu
  with_items:
    - "{{ the_user_dir }}/bin"

- name: Install ~/bin tools
  copy:
    src: bin/
    dest: "{{ the_user_dir }}/bin"
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Install ~/.dot helpers
  copy:
    src: home/_{{ item }}
    dest: "{{ the_user_dir }}/.{{ item }}"
    owner: ubuntu
    group: ubuntu
    mode: 0644
  with_items:
    - ackrc
    - agignore
    - bash_aliases
    - functions

- name: Install ~/.dot ex
  copy:
    src: homeex/_{{ item }}
    dest: "{{ the_user_dir }}/._{{ item }}"
    owner: ubuntu
    group: ubuntu
    mode: 0644
  with_items:
    - bashrc
    - profile

# TODO: set HISTCONTROL=ignorespace:ignoredups:erasedups   in ~/.bashrc
# TODO: set HISTSIZE=10000
# TODO: set HISTFILESIZE=20000


- name: Add our bashrc to the end of .bashrc
  blockinfile:
    path: "{{ the_user_dir }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      if [ -f ~/._bashrc ]; then
        . ~/._bashrc
      fi
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: Add our profile to the end of .profile
  blockinfile:
    path: "{{ the_user_dir }}/.profile"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      if [ -f ~/._profile ]; then
        . ~/._profile
      fi
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: Include vim tasks
  include_tasks: vim.yml

- name: Include vimcat tasks
  include_tasks: vimcat.yml
  when: not slim

- name: Include git config
  include_tasks: git.yml

    #- name: Print some debug information
    #  vars:
    #    msg: |
    #        Module Variables ("vars"):
    #        --------------------------------
    #        {{ vars | to_nice_json }}
    #
    #        Environment Variables ("environment"):
    #        --------------------------------
    #        {{ environment | to_nice_json }}
    #
    #        GROUP NAMES Variables ("group_names"):
    #        --------------------------------
    #        {{ group_names | to_nice_json }}
    #
    #        GROUPS Variables ("groups"):
    #        --------------------------------
    #        {{ groups | to_nice_json }}
    #
    #        HOST Variables ("hostvars"):
    #        --------------------------------
    #        {{ hostvars | to_nice_json }}
    #
    #  debug:
    #    msg: "{{ msg.split('\n') }}"
    #  tags: debug_info

    #- debug:
    #    var: vars
    #
    #- debug:
    #    var: environment
    #
    #- debug:
    #    var: group_names
    #
    #- debug:
    #    var: groups
    #
    #- debug:
    #    var: hostvars

...

