---

- name: Add vim8
  apt_repository:
    repo: ppa:jonathonf/vim
    state: present
  become: true

- name: Install vim package
  apt:
    name: vim
    state: latest
    update_cache: yes
  become: true

- name: Install .vimrc
  copy:
    src: _vimrc
    dest: "{{ the_user_dir }}/.vimrc"

- name: Setup vim
  args:
    executable: /bin/bash
    creates:    "{{ the_user_dir }}/.vim/bundle/vim-graphql/autoload/graphql.vim"
  shell: |
    set -x
    echo Installing vim

    pathogen() {
      git_user="$1"
      module="$2"

      # (***)
      if ! [[ -d {{ the_user_dir }}/.vim/bundle/${module} ]]; then
        (cd {{ the_user_dir }}/.vim/bundle && git clone --depth=1 https://github.com/${git_user}/${module}.git)
      fi
    }

    # VIM setup
    mkdir -p {{ the_user_dir }}/.vim/autoload {{ the_user_dir }}/.vim/bundle

    test -f {{ the_user_dir }}/.vim/autoload/pathogen.vim || curl -SLso {{ the_user_dir }}/.vim/autoload/pathogen.vim https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim

    #pathogen vim-ctrlspace vim-ctrlspace
    pathogen scrooloose syntastic
    pathogen mxw vim-jsx
    pathogen pangloss vim-javascript
    pathogen rust-lang rust.vim
    pathogen kballard vim-swift
    pathogen tpope vim-markdown
    pathogen jneen ragel.vim
    pathogen chr4 nginx.vim
    pathogen kkoomen vim-doge

    # Support for ag
    pathogen rking ag.vim
    pathogen Chun-Yang vim-action-ag

    # Support for ack
    pathogen mileszs ack.vim

    # Support for graphql
    pathogen jparise vim-graphql

    # vim-javascript and vim-jsx do horrible indentation
    # (***)
    if [[ -d {{ the_user_dir }}/.vim/bundle/vim-javascript/indent ]]; then
      rm -rf {{ the_user_dir }}/.vim/bundle/vim-javascript/indent
      rm -f {{ the_user_dir }}/.vim/bundle/vim-jsx/after/indent/jsx.vim
    fi


...

