---

- name: Vimcat deps -- pandoc
  apt:
    name:
      - pandoc
      - build-essential
    update_cache: true
  become: true

- name: Vimcat deps -- doctoc
  npm:
    name: doctoc
    global: true
  become: true


# Do we have the vimcat binary?
- stat:
    path: /usr/bin/vimcat
  register: vimcat_binary


- debug:
    msg: "vimcat_binary isn't defined (path doesn't exist)"
  when: vimcat_binary.stat.islnk is not defined

- debug:
    msg: "vimcat_binary is defined (path must exist)"
  when: vimcat_binary.stat.islnk is defined

- debug:
    msg: "Path exists and is a symlink"
  when: vimcat_binary.stat.islnk is defined and vimcat_binary.stat.islnk

- debug:
    msg: "Path exists and isn't a symlink"
  when: vimcat_binary.stat.islnk is defined and vimcat_binary.stat.islnk == False

- debug:
  var: vimcat_binary

- name: Make/Install vimcat
  block:

    - name: Clone vimcat repo
      git:
        repo: https://github.com/rkitover/vimpager
        dest: "{{ ansible_user_dir }}/zz_packages/build/vimpager"

    - name: Build vimcat
      make:
        chdir: "{{ ansible_user_dir }}/zz_packages/build/vimpager"
        target: install-deb
      become: true

  when: vimcat_binary.stat.executable is defined and vimcat_binary.stat.executable == False

...

