---

- name: Vimcat deps -- pandoc
  apt:
    name:
      - pandoc
      - build-essential
    update_cache: true
  become: true

- name: Vimcat deps -- doctoc
  npm:
    name: doctoc
    global: true
  become: true


# Do we have the vimcat binary?
- stat:
    path: /usr/bin/vimcat
  register: vimcat_binary

- name: Make/Install vimcat
  block:

    - name: Clone vimcat repo
      git:
        repo: https://github.com/rkitover/vimpager
        dest: "{{ ansible_user_dir }}/zz_packages/build/vimpager"

    - name: Build vimcat
      make:
        chdir: "{{ ansible_user_dir }}/zz_packages/build/vimpager"
        target: install-deb
      become: true

  when: vimcat_binary.stat.executable is not defined or vimcat_binary.stat.executable == False

...

